tasks:
  - init: |
      echo 'TODO: build project'
      python3 -m venv /workspace/BATTLESHIP/.venv
      source /workspace/BATTLESHIP/.venv/bin/activate
      python3 -m pip install --upgrade pip
      pip install -r requirements.txt
      deactivate
    command: |
      echo 'TODO: start app'
      source /workspace/BATTLESHIP/.venv/bin/activate
  - command: |
      source /workspace/BATTLESHIP/.venv/bin/activate
      python3 server.py "Endpoint=https://bship-pubsub.webpubsub.azure.com;AccessKey=IfH+PhpLe5YR/CM27jVIowgmm1VVIT2pgUqbN2YJRW8=;Version=1.0;"
ports:
  - port: 8080

vscode:
  extensions:
    - ms-python.python